name: CD-build
on:
  push:
    branches:
      - 'master'

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
  SERVICE_NAME: kanyui

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      # Build and publish the Docker image to Google Container Registry
      - name: Build and Publish
        env:
          CLOUDSDK_CORE_PROJECT: $PROJECT_ID
        run: |
          gcloud builds submit --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud components install beta && \
          gcloud beta run deploy "$SERVICE_NAME" --quiet \
                                        --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
                                        --project "$PROJECT_ID" \
                                        --region europe-west1 \
                                        --platform managed \
                                        --memory 128Mi \
                                        --timeout=300 \
                                        --concurrency=2